site_name: HFUT-XC计算机科学与技术资料汇总
site_description: 这是合肥工业大学宣城校区计算机科学与技术资料汇总的网站
site_author: Tuning-Luna

repo_url: https://github.com/Tuning-Luna/HFUT_XC_Study_Things
edit_uri: ""

theme:
  name: material
  logo: assets/hfut.png     # 左上角网站 logo
  favicon: assets/hfut.png   # 浏览器标签页图标
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - palette.toggle   # 显示切换按钮
    - palette.auto     # 自动跟随系统深浅色模式



# 附加信息
extra:
  meta:
    - name: keywords
      content: "HFUT, 合肥工业大学, 宣城校区, 计算机科学与技术, 教材, 课件, PPT, PDF"
    - name: description
      content: "合肥工业大学宣城校区计算机科学与技术资料汇总，包括课程 PPT、实验资料、讲义和代码示例。"
